/// Two-component bi-exponential fitting: extract tau_rise and tau_decay from a free-form kernel.
///
/// # Physical motivation
///
/// Iterative deconvolution alternates between two steps:
///   1. **Spike solve**: given a kernel K, find spikes s that explain the trace y ≈ K*s + b
///   2. **Kernel solve**: given spikes s, re-estimate the free-form kernel h_free
///
/// The spike solver detects events by correlating the trace with the current kernel.
/// Where noise happens to correlate with the kernel's rising edge (bins 1-3), the
/// solver produces false-positive spikes. When these spurious spikes are fed back
/// into kernel estimation, they imprint an artifact onto h_free whose shape is a
/// compressed (time-scaled) version of the detection kernel itself — because the
/// false positives were generated by correlation with that kernel.
///
/// A single biexponential fit would try to explain both the true calcium kernel and
/// this artifact with one curve, causing tau_rise to collapse toward zero. The
/// two-component model explicitly separates them.
///
/// # Model
///
/// Fits h(t) = beta_s * T_s(t) + beta_f * T_f(t)
/// where:
/// - **Slow component** (calcium kernel): T_s(t) = exp(-t/tau_d) - exp(-t/tau_r)
/// - **Fast component** (noise artifact):  T_f(t) = exp(-t/(tau_d·r)) - exp(-t/(tau_r·r))
///
/// The fast component is a compressed biexponential — the same shape as the slow
/// component, time-scaled by factor r < 1. This physically matches the artifact's
/// origin: false-positive spikes generated by the slow kernel produce an artifact
/// shaped like a compressed copy of that kernel.
///
/// Both components are 0 at t=0 by the biexponential identity (exp(0)-exp(0)=0),
/// so no skip or null hacks are needed at bin 0.
///
/// When no artifact exists, beta_f converges to ~0, recovering the single-biexp result.
///
/// Uses grid search over (tau_r, tau_d, r) with 2-variable NNLS for (beta_s, beta_f),
/// optionally refined by golden-section search.

#[cfg_attr(feature = "jsbindings", derive(serde::Serialize))]
pub struct BiexpResult {
    pub tau_rise: f64,
    pub tau_decay: f64,
    pub beta: f64,
    pub residual: f64,
    pub r_fast: f64,
    pub beta_fast: f64,
}

/// Fit a two-component bi-exponential model to a free-form kernel.
///
/// Uses a 20x20x8 log-spaced grid search over (tau_r, tau_d, r) with
/// 2-variable NNLS at each grid point, followed by optional golden-section
/// refinement around the best grid point.
///
/// Arguments:
/// - `h_free`: the free-form kernel to fit (from estimate_free_kernel)
/// - `fs`: sampling rate used for the kernel
/// - `refine`: whether to apply golden-section refinement after grid search
/// - `skip`: number of early kernel samples to exclude from the least-squares fit
pub fn fit_biexponential(h_free: &[f32], fs: f64, refine: bool, skip: usize) -> BiexpResult {
    let n = h_free.len();
    let skip = skip.min(n.saturating_sub(1));
    if n == 0 {
        return BiexpResult {
            tau_rise: 0.02,
            tau_decay: 0.4,
            beta: 0.0,
            residual: f64::INFINITY,
            r_fast: 0.0,
            beta_fast: 0.0,
        };
    }

    let dt = 1.0 / fs;

    // Grid search ranges (in seconds).
    // tau_r lower bound: at least 2 samples (Nyquist floor). A rise time shorter
    // than 2/fs is unresolvable and drives the iterative loop toward collapse.
    let tau_r_lo = (2.0 / fs).max(0.005_f64);
    let tau_r_hi = 0.5_f64;
    let tau_d_lo = 0.05_f64;
    let tau_d_hi = 5.0_f64;

    // Fast component compression ratio r.
    // Upper bound 0.2: the fast template peaks at ≤20% of the slow peak time,
    // confining it to bins 0-2. This keeps the two templates well-separated in
    // the NNLS — at higher r the compressed biexponential becomes broad enough
    // to approximate a different biexponential, causing collinear degeneracy.
    // Lower bound per grid point: r_lo = max(dt/tau_r, 0.02) ensures the fast
    // rise time tau_r*r spans at least 1 sample.
    let r_hi = 0.2_f64;
    let r_grid_n = 8;

    let grid_n = 20;
    let log_tr_lo = tau_r_lo.ln();
    let log_tr_hi = tau_r_hi.ln();
    let log_td_lo = tau_d_lo.ln();
    let log_td_hi = tau_d_hi.ln();

    let mut best = BiexpResult {
        tau_rise: 0.02,
        tau_decay: 0.4,
        beta: 0.0,
        residual: f64::INFINITY,
        r_fast: 0.0,
        beta_fast: 0.0,
    };

    // Phase 1: Grid search over (tau_r, tau_d, r).
    for i in 0..grid_n {
        let log_tr = log_tr_lo + (log_tr_hi - log_tr_lo) * i as f64 / (grid_n - 1) as f64;
        let tau_r = log_tr.exp();

        for j in 0..grid_n {
            let log_td = log_td_lo + (log_td_hi - log_td_lo) * j as f64 / (grid_n - 1) as f64;
            let tau_d = log_td.exp();

            // Enforce tau_d > tau_r
            if tau_d <= tau_r {
                continue;
            }

            // r_lo: fast rise time tau_r*r must be ≥ 1 sample, with floor of 0.02
            let r_lo = (dt / tau_r).max(0.02);
            if r_lo < r_hi {
                // Scan r values in log-space
                let log_r_lo = r_lo.ln();
                let log_r_hi = r_hi.ln();
                for k in 0..r_grid_n {
                    let log_r =
                        log_r_lo + (log_r_hi - log_r_lo) * k as f64 / (r_grid_n - 1) as f64;
                    let r = log_r.exp();

                    let (beta_s, beta_f, residual) =
                        eval_two_component(h_free, tau_r, tau_d, r, dt, skip);
                    if residual < best.residual {
                        best = BiexpResult {
                            tau_rise: tau_r,
                            tau_decay: tau_d,
                            beta: beta_s,
                            residual,
                            r_fast: r,
                            beta_fast: beta_f,
                        };
                    }
                }
            } else {
                // No valid r range — fit without fast component
                let (beta_s, residual) = eval_slow_only(h_free, tau_r, tau_d, dt, skip);
                if residual < best.residual {
                    best = BiexpResult {
                        tau_rise: tau_r,
                        tau_decay: tau_d,
                        beta: beta_s,
                        residual,
                        r_fast: 0.0,
                        beta_fast: 0.0,
                    };
                }
            }
        }
    }

    // Phase 2: Optional golden-section refinement
    if refine {
        let (refined_tr, refined_td, refined_r) =
            golden_section_refine(h_free, &best, dt, 30, skip);
        let (beta_s, beta_f, residual) =
            eval_two_component(h_free, refined_tr, refined_td, refined_r, dt, skip);
        if residual < best.residual {
            best = BiexpResult {
                tau_rise: refined_tr,
                tau_decay: refined_td,
                beta: beta_s,
                residual,
                r_fast: refined_r,
                beta_fast: beta_f,
            };
        }
    }

    // Recompute residual over the FULL kernel (skip=0) so it captures early-bin
    // divergence. When skip=0 this is a no-op (both components are 0 at t=0).
    if skip > 0 {
        let (_, _, full_residual) = eval_two_component(
            h_free,
            best.tau_rise,
            best.tau_decay,
            best.r_fast,
            dt,
            0,
        );
        best.residual = full_residual;
    }

    best
}

/// Evaluate two-component fit at fixed (tau_r, tau_d, r) with NNLS for (beta_s, beta_f).
///
/// Model: h(t) = beta_s * (exp(-t/tau_d) - exp(-t/tau_r))
///              + beta_f * (exp(-t/(tau_d*r)) - exp(-t/(tau_r*r)))
///
/// The fast component is a compressed biexponential with the same shape as the slow
/// component, time-scaled by factor r. Both are 0 at t=0 by construction.
///
/// For fixed time constants, this is a 2-variable non-negative least squares problem.
/// We enumerate all 4 active sets and pick the one with minimum residual.
///
/// Returns (beta_s, beta_f, residual).
fn eval_two_component(
    h_free: &[f32],
    tau_r: f64,
    tau_d: f64,
    r: f64,
    dt: f64,
    skip: usize,
) -> (f64, f64, f64) {
    let n = h_free.len();

    // Gram matrix G (2x2), rhs vector (2x1), and ||h||^2
    let mut g_ss = 0.0_f64; // <T_s, T_s>
    let mut g_ff = 0.0_f64; // <T_f, T_f>
    let mut g_sf = 0.0_f64; // <T_s, T_f>
    let mut rhs_s = 0.0_f64; // <h, T_s>
    let mut rhs_f = 0.0_f64; // <h, T_f>
    let mut dot_hh = 0.0_f64; // <h, h>

    let r_active = r > 1e-10;

    for i in skip..n {
        let t = i as f64 * dt;
        let ts = (-t / tau_d).exp() - (-t / tau_r).exp();
        let tf = if r_active {
            (-t / (tau_d * r)).exp() - (-t / (tau_r * r)).exp()
        } else {
            0.0
        };
        let hi = h_free[i] as f64;

        g_ss += ts * ts;
        g_ff += tf * tf;
        g_sf += ts * tf;
        rhs_s += hi * ts;
        rhs_f += hi * tf;
        dot_hh += hi * hi;
    }

    // Compute residual: ||h - beta_s*T_s - beta_f*T_f||^2
    // = ||h||^2 - 2*beta_s*<h,T_s> - 2*beta_f*<h,T_f>
    //   + beta_s^2*<T_s,T_s> + 2*beta_s*beta_f*<T_s,T_f> + beta_f^2*<T_f,T_f>
    let residual_fn = |bs: f64, bf: f64| -> f64 {
        dot_hh - 2.0 * bs * rhs_s - 2.0 * bf * rhs_f
            + bs * bs * g_ss
            + 2.0 * bs * bf * g_sf
            + bf * bf * g_ff
    };

    let mut best_bs = 0.0;
    let mut best_bf = 0.0;
    let mut best_res = dot_hh; // residual when both are zero

    // Active set 1: both free — solve 2x2 system via Cramer's rule
    // Require bs >= bf: the slow component (calcium signal) must dominate the
    // fast component (noise artifact correction). Without this, the compressed
    // biexponential can steal the slow signal at wrong (tau_r, tau_d) grid points.
    let det = g_ss * g_ff - g_sf * g_sf;
    if det.abs() > 1e-30 {
        let bs = (rhs_s * g_ff - rhs_f * g_sf) / det;
        let bf = (rhs_f * g_ss - rhs_s * g_sf) / det;
        if bs >= 0.0 && bf >= 0.0 && bs >= bf {
            let r = residual_fn(bs, bf);
            if r < best_res {
                best_bs = bs;
                best_bf = bf;
                best_res = r;
            }
        }
    }

    // Active set 2: beta_s only (beta_f = 0)
    if g_ss > 1e-30 {
        let bs = rhs_s / g_ss;
        if bs >= 0.0 {
            let r = residual_fn(bs, 0.0);
            if r < best_res {
                best_bs = bs;
                best_bf = 0.0;
                best_res = r;
            }
        }
    }

    // Active set 3 (beta_f only) is NOT tried: the fast component is a correction
    // for noise artifacts and should never appear without the slow component.

    // Active set 4: both zero — already covered by initial best_res = dot_hh

    (best_bs, best_bf, best_res)
}

/// Evaluate slow-only fit at fixed (tau_r, tau_d) with scalar NNLS for beta_s.
/// Returns (beta_s, residual).
fn eval_slow_only(h_free: &[f32], tau_r: f64, tau_d: f64, dt: f64, skip: usize) -> (f64, f64) {
    let n = h_free.len();
    let mut g_ss = 0.0_f64;
    let mut rhs_s = 0.0_f64;
    let mut dot_hh = 0.0_f64;

    for i in skip..n {
        let t = i as f64 * dt;
        let ts = (-t / tau_d).exp() - (-t / tau_r).exp();
        let hi = h_free[i] as f64;
        g_ss += ts * ts;
        rhs_s += hi * ts;
        dot_hh += hi * hi;
    }

    if g_ss > 1e-30 {
        let bs = (rhs_s / g_ss).max(0.0);
        let residual = dot_hh - 2.0 * bs * rhs_s + bs * bs * g_ss;
        (bs, residual)
    } else {
        (0.0, dot_hh)
    }
}

/// Golden-section refinement around the best grid point.
/// Cycles through refining tau_r, tau_d, and r for `max_steps` total.
fn golden_section_refine(
    h_free: &[f32],
    best: &BiexpResult,
    dt: f64,
    max_steps: usize,
    skip: usize,
) -> (f64, f64, f64) {
    let phi = (5.0_f64.sqrt() - 1.0) / 2.0; // golden ratio conjugate

    let mut tau_r = best.tau_rise;
    let mut tau_d = best.tau_decay;
    let mut r = best.r_fast;

    // If r_fast is zero (no fast component), skip r refinement
    let has_fast = r > 0.0;

    for step in 0..max_steps {
        let phase = if has_fast { step % 3 } else { step % 2 };

        if phase == 0 {
            // Refine tau_r (floor at 2 samples — same Nyquist limit as grid search)
            let mut lo = (tau_r * 0.5).max(2.0 * dt);
            let mut hi = tau_r * 2.0;
            // Ensure tau_r < tau_d
            hi = hi.min(tau_d * 0.99);
            if lo >= hi {
                continue;
            }

            for _ in 0..10 {
                let x1 = hi - phi * (hi - lo);
                let x2 = lo + phi * (hi - lo);
                let (_, _, r1) = eval_two_component(h_free, x1, tau_d, r, dt, skip);
                let (_, _, r2) = eval_two_component(h_free, x2, tau_d, r, dt, skip);
                if r1 < r2 {
                    hi = x2;
                } else {
                    lo = x1;
                }
            }
            tau_r = (lo + hi) / 2.0;
        } else if phase == 1 {
            // Refine tau_d
            let mut lo = (tau_d * 0.5).max(tau_r * 1.01);
            let mut hi = tau_d * 2.0;
            if lo >= hi {
                continue;
            }

            for _ in 0..10 {
                let x1 = hi - phi * (hi - lo);
                let x2 = lo + phi * (hi - lo);
                let (_, _, r1) = eval_two_component(h_free, tau_r, x1, r, dt, skip);
                let (_, _, r2) = eval_two_component(h_free, tau_r, x2, r, dt, skip);
                if r1 < r2 {
                    hi = x2;
                } else {
                    lo = x1;
                }
            }
            tau_d = (lo + hi) / 2.0;
        } else {
            // Refine r with bounds [max(r*0.5, 0.02), min(r*2.0, 0.2)]
            let mut lo = (r * 0.5).max(0.02);
            let mut hi = (r * 2.0).min(0.2);
            if lo >= hi {
                continue;
            }

            for _ in 0..10 {
                let x1 = hi - phi * (hi - lo);
                let x2 = lo + phi * (hi - lo);
                let (_, _, r1) = eval_two_component(h_free, tau_r, tau_d, x1, dt, skip);
                let (_, _, r2) = eval_two_component(h_free, tau_r, tau_d, x2, dt, skip);
                if r1 < r2 {
                    hi = x2;
                } else {
                    lo = x1;
                }
            }
            r = (lo + hi) / 2.0;
        }
    }

    (tau_r, tau_d, r)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate a bi-exponential kernel with known parameters.
    fn make_biexp(tau_r: f64, tau_d: f64, beta: f64, fs: f64, n: usize) -> Vec<f32> {
        let dt = 1.0 / fs;
        (0..n)
            .map(|i| {
                let t = i as f64 * dt;
                (beta * ((-t / tau_d).exp() - (-t / tau_r).exp())) as f32
            })
            .collect()
    }

    /// Generate a two-component kernel with known parameters.
    /// Fast component is a compressed biexponential: same shape as slow, scaled by r.
    fn make_two_component(
        tau_r: f64,
        tau_d: f64,
        beta_s: f64,
        r: f64,
        beta_f: f64,
        fs: f64,
        n: usize,
    ) -> Vec<f32> {
        let dt = 1.0 / fs;
        (0..n)
            .map(|i| {
                let t = i as f64 * dt;
                let slow = beta_s * ((-t / tau_d).exp() - (-t / tau_r).exp());
                let fast = beta_f * ((-t / (tau_d * r)).exp() - (-t / (tau_r * r)).exp());
                (slow + fast) as f32
            })
            .collect()
    }

    #[test]
    fn recovers_known_taus() {
        let tau_r_true = 0.08;
        let tau_d_true = 0.5;
        let fs = 30.0;
        let n = 60; // 2 seconds
        let h = make_biexp(tau_r_true, tau_d_true, 2.0, fs, n);

        let result = fit_biexponential(&h, fs, true, 0);

        let tr_err = (result.tau_rise - tau_r_true).abs() / tau_r_true;
        let td_err = (result.tau_decay - tau_d_true).abs() / tau_d_true;

        assert!(
            tr_err < 0.15,
            "Tau rise error {:.1}% (got {:.4}, expected {:.4})",
            tr_err * 100.0,
            result.tau_rise,
            tau_r_true
        );
        assert!(
            td_err < 0.15,
            "Tau decay error {:.1}% (got {:.4}, expected {:.4})",
            td_err * 100.0,
            result.tau_decay,
            tau_d_true
        );
    }

    #[test]
    fn clean_biexp_has_near_zero_beta_fast() {
        let h = make_biexp(0.08, 0.5, 2.0, 30.0, 60);
        let result = fit_biexponential(&h, 30.0, true, 0);

        // For a clean biexponential input, beta_fast should be negligible
        assert!(
            result.beta_fast < 0.1 * result.beta,
            "beta_fast ({:.4}) should be much smaller than beta ({:.4}) for clean biexp input",
            result.beta_fast,
            result.beta
        );
    }

    #[test]
    fn tau_d_greater_than_tau_r() {
        let h = make_biexp(0.05, 0.8, 1.5, 30.0, 60);
        let result = fit_biexponential(&h, 30.0, true, 0);

        assert!(
            result.tau_decay > result.tau_rise,
            "tau_d ({}) should be > tau_r ({})",
            result.tau_decay,
            result.tau_rise
        );
    }

    #[test]
    fn refinement_improves_fit() {
        let h = make_biexp(0.04, 0.6, 2.0, 30.0, 60);

        let coarse = fit_biexponential(&h, 30.0, false, 0);
        let refined = fit_biexponential(&h, 30.0, true, 0);

        assert!(
            refined.residual <= coarse.residual + 1e-10,
            "Refinement should not worsen fit: refined {} vs coarse {}",
            refined.residual,
            coarse.residual
        );
    }

    #[test]
    fn empty_kernel() {
        let result = fit_biexponential(&[], 30.0, true, 0);
        assert_eq!(result.residual, f64::INFINITY);
    }

    #[test]
    fn positive_beta() {
        let h = make_biexp(0.02, 0.4, 3.0, 30.0, 40);
        let result = fit_biexponential(&h, 30.0, false, 0);

        assert!(
            result.beta > 0.0,
            "Beta should be positive for standard calcium kernel, got {}",
            result.beta
        );
    }

    #[test]
    fn various_parameter_ranges() {
        // Test with fast dynamics
        let h_fast = make_biexp(0.01, 0.1, 1.0, 100.0, 50);
        let r = fit_biexponential(&h_fast, 100.0, true, 0);
        assert!(r.tau_decay > r.tau_rise);
        assert!(r.residual < 1.0); // should fit well

        // Test with slow dynamics
        let h_slow = make_biexp(0.1, 2.0, 1.0, 10.0, 50);
        let r = fit_biexponential(&h_slow, 10.0, true, 0);
        assert!(r.tau_decay > r.tau_rise);
    }

    #[test]
    fn skip_ignores_early_samples() {
        let tau_r_true = 0.08;
        let tau_d_true = 0.5;
        let fs = 30.0;
        let n = 60;
        let mut h = make_biexp(tau_r_true, tau_d_true, 2.0, fs, n);

        // Corrupt first 3 samples with high-frequency noise
        h[0] = 10.0;
        h[1] = -5.0;
        h[2] = 8.0;

        // Without skip: noise biases the fit
        let no_skip = fit_biexponential(&h, fs, true, 0);

        // With skip=3: noise is excluded from fitting, tau estimates improve
        let with_skip = fit_biexponential(&h, fs, true, 3);

        let err_no_skip = (no_skip.tau_rise - tau_r_true).abs();
        let err_with_skip = (with_skip.tau_rise - tau_r_true).abs();

        assert!(
            err_with_skip < err_no_skip,
            "skip=3 should improve tau_rise fit: err_skip={:.4} vs err_noskip={:.4}",
            err_with_skip,
            err_no_skip
        );

        // The residual should be evaluated over the FULL kernel (including
        // corrupted bins), so it reflects the total mismatch. With corrupted
        // early bins, the full-kernel residual should be larger than the
        // residual from a clean kernel.
        let clean = make_biexp(tau_r_true, tau_d_true, 2.0, fs, n);
        let clean_result = fit_biexponential(&clean, fs, true, 3);
        assert!(
            with_skip.residual > clean_result.residual,
            "Corrupted kernel should have higher full-kernel residual: {:.6} vs {:.6}",
            with_skip.residual,
            clean_result.residual
        );
    }

    #[test]
    fn recovers_taus_with_fast_component() {
        // Generate two-component kernel with compressed biexp fast component (r=0.1)
        let tau_r_true = 0.08;
        let tau_d_true = 0.5;
        let r_true = 0.1;
        let fs = 100.0; // high fs to resolve fast component
        let n = 200;
        let h = make_two_component(tau_r_true, tau_d_true, 2.0, r_true, 1.5, fs, n);

        let result = fit_biexponential(&h, fs, true, 0);

        // Slow tau values should be recovered
        let tr_err = (result.tau_rise - tau_r_true).abs() / tau_r_true;
        let td_err = (result.tau_decay - tau_d_true).abs() / tau_d_true;

        assert!(
            tr_err < 0.25,
            "Tau rise error {:.1}% (got {:.4}, expected {:.4})",
            tr_err * 100.0,
            result.tau_rise,
            tau_r_true
        );
        assert!(
            td_err < 0.25,
            "Tau decay error {:.1}% (got {:.4}, expected {:.4})",
            td_err * 100.0,
            result.tau_decay,
            tau_d_true
        );

        // Fast component should be detected
        assert!(
            result.beta_fast > 0.0,
            "beta_fast should be positive when fast component exists, got {}",
            result.beta_fast
        );
    }

    #[test]
    fn fast_absorbs_noise_spike() {
        let tau_r_true = 0.08;
        let tau_d_true = 0.5;
        let fs = 100.0; // high fs needed to resolve fast vs slow components
        let n = 200;
        let mut h = make_biexp(tau_r_true, tau_d_true, 2.0, fs, n);

        // Simulate noise artifact: large values at bins 0-2
        h[0] += 5.0;
        h[1] += 3.0;
        h[2] += 1.0;

        let result = fit_biexponential(&h, fs, true, 0);

        // With two-component model, tau_rise should stay near true value
        // because the fast component absorbs the noise spike
        let tr_err = (result.tau_rise - tau_r_true).abs() / tau_r_true;
        assert!(
            tr_err < 0.5,
            "tau_rise should stay near true value with noise spike: got {:.4} (err {:.1}%), expected {:.4}",
            result.tau_rise,
            tr_err * 100.0,
            tau_r_true
        );

        // The fast component should have picked up the spike
        assert!(
            result.beta_fast > 0.0,
            "beta_fast should be positive to absorb the noise spike"
        );
    }

    #[test]
    fn r_fast_in_valid_range() {
        // For various inputs, verify 0 < r_fast ≤ 0.5 always holds (when r_fast > 0)
        let test_cases = [
            (0.08, 0.5, 30.0),
            (0.05, 0.3, 100.0),
            (0.1, 2.0, 10.0),
        ];

        for (tau_r, tau_d, fs) in test_cases {
            let h = make_biexp(tau_r, tau_d, 2.0, fs, 60);
            let result = fit_biexponential(&h, fs, true, 0);

            if result.r_fast > 0.0 {
                assert!(
                    result.r_fast <= 0.2,
                    "r_fast ({}) should be ≤ 0.2 for (tau_r={}, tau_d={}, fs={})",
                    result.r_fast,
                    tau_r,
                    tau_d,
                    fs
                );
            }
        }
    }

    #[test]
    fn nnls_active_sets() {
        let fs = 100.0;
        let dt = 1.0 / fs;
        let n = 100;
        let r = 0.1; // compression ratio for fast component

        // Case 1: Pure slow component — should yield beta_s > 0, beta_f ≈ 0
        let h_slow = make_biexp(0.05, 0.5, 2.0, fs, n);
        let (bs, bf, _) = eval_two_component(&h_slow, 0.05, 0.5, r, dt, 0);
        assert!(bs > 0.0, "beta_s should be positive for slow-only input");
        assert!(
            bf < 0.1 * bs,
            "beta_f ({:.4}) should be near zero for slow-only input (beta_s={:.4})",
            bf,
            bs
        );

        // Case 2: Pure fast component (compressed biexp) — the NNLS does NOT try
        // beta_f-only, so it falls back to beta_s-only (imperfect fit) or zero.
        // This is by design: the fast component is a correction, not a standalone signal.
        let h_fast: Vec<f32> = (0..n)
            .map(|i| {
                let t = i as f64 * dt;
                (3.0 * ((-t / (0.5 * r)).exp() - (-t / (0.05 * r)).exp())) as f32
            })
            .collect();
        let (bs, _bf, _) = eval_two_component(&h_fast, 0.05, 0.5, r, dt, 0);
        // With no fast-only active set, the slow template absorbs what it can
        assert!(bs >= 0.0, "beta_s should be non-negative for any input");

        // Case 3: Both components present
        let h_both = make_two_component(0.05, 0.5, 2.0, r, 1.5, fs, n);
        let (bs, bf, _) = eval_two_component(&h_both, 0.05, 0.5, r, dt, 0);
        assert!(bs > 0.0, "beta_s should be positive for mixed input");
        assert!(bf > 0.0, "beta_f should be positive for mixed input");

        // Case 4: Zero signal — both should be zero
        let h_zero = vec![0.0_f32; n];
        let (bs, bf, res) = eval_two_component(&h_zero, 0.05, 0.5, r, dt, 0);
        assert_eq!(bs, 0.0, "beta_s should be zero for zero input");
        assert_eq!(bf, 0.0, "beta_f should be zero for zero input");
        assert!(res < 1e-20, "residual should be ~0 for zero input");
    }
}
